### ISSUE TITLE
Can you put some examples for using this crate?

### ISSUE THREAD

**Issue by gudsaf** [Devolutions/sspi-rs#1]
I looked at test in crate repos, but can't find any examples with using SspiProvider. 
Can you add awesome or write some brief in Readme.md?

**Comment by vaffeine** [comment]
Hi @gudsaf 

I am glad you are interested in this crate. It's not really mature yet - previously it was just a part of https://github.com/Devolutions/devolutions-jet, so we lack documentation and examples. But you can look how it is used in https://github.com/Devolutions/devolutions-jet.

In short, `SspiProvider` is not in a public interface, but you can use higher level `CredSsp` structure if it works for you. `Ntlm` is not public now, and we need to think about making it public with more convenient to use interface.

Also, I added some text to rustdoc that might help to understand how to use this library.

**Comment by awakecoding** [comment]
@gudsaf to add to what @vaffeine said, sspi-rs is also currently used in https://github.com/Devolutions/ldap3/tree/spnego

**Comment by gudsaf** [comment]
@vaffeine, @awakecoding will look at, thanks for comments!
