### ISSUE TITLE
NTLM without random Session Key

### ISSUE THREAD

**Issue by ndrsg** [Devolutions/sspi-rs#113]
Hi there,

I'm implementing "NTLM over HTTP" and use sspi-rs to process the NTLM Messages.
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-ntht/f09cf6e1-529e-403b-a8a5-7368ee096a6a

I'm using actix-web as web-server and chrome as NTLM client.

So far the process works until a valid looking NTLMSSP_AUTH Message (Step 3), but it does not have a "Random Session Key" inside.

I've traced the messages, and it seems, that Chrome sends the NEGOTIATE message without "Negotiate Key Exchange" Flag, so it is valid, that the Random Session Key is not inside the AUTHENTICATE message.

However, the "read_header" function of authenticate.rs stumbles over this line:

https://github.com/Devolutions/sspi-rs/blob/master/src/ntlm/messages/server/authenticate.rs#L96
```rs
if encrypted_random_session_key.buffer.len() != ENCRYPTED_RANDOM_SESSION_KEY_SIZE {
    return Err(crate::Error::new(
        crate::ErrorKind::InvalidToken,
        String::from("Invalid encrypted random session key"),
    ));
}
```

hence
```
pub const ENCRYPTED_RANDOM_SESSION_KEY_SIZE: usize = 16;
```

I'm wondering:
- should the session-key size or the check at all here depend on the NEGOTIATE_KEY_EXCHANGE flag?
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/f9e6fbc4-a953-4f24-b229-ccdcc213b9ec
> If NTLMSSP_NEGOTIATE_KEY_EXCH is set, the server MUST check if client supplied a valid EncryptedRandomSessionKey in the AUTHENTICATE_MESSAGE (section 2.2.1.3); otherwise, the server MUST return SEC_E_INVALID_TOKEN.

- do I have to modify the AUTHENTICATE message before passing it to ntlm, like calculating the encrypted session key manually on serverside?

Any comments are highly appreciated :)

**Comment by RRRadicalEdward** [comment]
Hi!
> should the session-key size or the check at all here depend on the NEGOTIATE_KEY_EXCHANGE flag? 

Yes, Ideally It should depend on in. The client side of the `NTLM` protocol checks if the flag is set or not(https://github.com/Devolutions/sspi-rs/blob/master/src/ntlm/messages/client/authenticate.rs#L186). But the server side doesn't, always require it and tries to read from incoming messages. 

> do I have to modify the AUTHENTICATE message before passing it to ntlm, like calculating the encrypted session key manually on serverside?

There are two options: 

- Set the session key in the AUTHENTICATE  message(workaround).
- You are welcome to contribute. PRs are highly appreciated. 
I think I will require to add an extra `if` in the `read_header` and add some extract checks in the `encrypt message` and `decrypt message` functions in case there is no session key, and modify https://github.com/Devolutions/sspi-rs/blob/master/src/ntlm/messages/server/authenticate.rs#L144 function as `encrypted_random_session_key` won't be present every time.

**Comment by ndrsg** [comment]
Okay, thanks! I will try to provide a PR.

I also tried your workaround, but its to difficult to manipulate the message but beside its really a pain to perform the bit operations correctly, it breaks on mic-check:
```Error { error_type: MessageAltered, description: "Message Integrity Check (MIC) verification failed!" }```

What to you think about typing the encrypted_random_session_key as an
```rs
Option<MessageFields>
```
and see where it takes us?

**Comment by RRRadicalEdward** [comment]
> What to you think about typing the encrypted_random_session_key as an 
> `Option<MessageFields>`
> and see where it takes us?

Sounds good
