### ISSUE TITLE
get_client_principal_realm should examine krb5.conf for domain_realm remapping

### ISSUE THREAD

**Issue by unreality** [Devolutions/sspi-rs#323]
Currently `get_client_principal_realm`: https://github.com/Devolutions/sspi-rs/blob/856428be06a29371308fe14e01eac88c418cbb5c/src/kerberos/client/generators.rs#L81 generates the kerberos realm by examining username@domain and assumes domain == realm. 

krb5.conf specifies the [domain_realm] section that allows for a given domain to have a different kerberos realm eg:
`
[domain_realm]
example.com = REALM.EXAMPLE.COM
`
`get_client_principal_realm` should either examine a krb5.conf to determine the correct realm, or have some other mechanism to specify the correct realm (environment variable perhaps?)

This would solve https://github.com/gravitational/teleport/issues/49173

**Comment by CBenoit** [comment]
I talked with @TheBestTvarynka, and he said it would be better to improve `get_client_principal_realm` by looking in the krb5.conf file. I assigned him the issue, he'll be working on that as soon as possible.

**Comment by CBenoit** [comment]
Fix is shipped with sspi v0.15.0 published today.
