### ISSUE TITLE
API to set Workstation for AuthIdentity

### ISSUE THREAD

**Issue by RickSKy** [Devolutions/sspi-rs#36]
In some case, may need  Workstation for negotiate, is there any interface for it.

**Comment by awakecoding** [comment]
@RickSKy do you know if there's a way to do it in the original Windows SSPI API? We've started adding a few extended credential/context attributes not supported in Windows SSPI, but we always try to find the "portable" way to do it first.

**Comment by RickSKy** [comment]
I found that cntlm has Workstation param  [Configuration hints](https://cntlm.sourceforge.net/).

**Comment by RickSKy** [comment]
we can also find workstation in  Python's ntlm lib https://pypi.org/project/ntlm-auth/

**Comment by RRRadicalEdward** [comment]
There is no API for it now, but we might add one for it

**Comment by CBenoit** [comment]
Hi @RRRadicalEdward! Is it on your roadmap for this month?

**Comment by RRRadicalEdward** [comment]
@CBenoit Yeah. I will do it after making the changes in FreeRDP that Richard has requested.

**Comment by CBenoit** [comment]
Excellent!
