### ISSUE TITLE
Support for trace logs at runtime

### ISSUE THREAD

**Issue by jborean93** [Devolutions/sspi-rs#85]
There is limited trace logging available with https://github.com/Devolutions/sspi-rs/pull/73 but it requires the user to have a binary compiled with `debug_mode` enabled. It would be great if there was a feature like [KRB5_TRACE](https://web.mit.edu/kerberos/krb5-latest/doc/admin/troubleshoot.html) that MIT krb5 supports. This is extremely useful when dealing with Kerberos problems and trying to figure out why things are not working. The benefit is that it's enabled even in the release builds so you don't need to tell users to replace this dll with something else, they just need to set an env var.

I have no idea if Rust has some general logging mechanism that could be used instead but ultimately what I am hoping for is a way to debug broken scenarios and getting logs from a user is pretty critical for this.

**Comment by thenextman** [comment]
@jborean93 The `debug_mode` was a quick fix to allow us to uncover the source of panics during integration (we hit similar issues to you in [83](https://github.com/Devolutions/sspi-rs/issues/83). 

I agree that a general purpose tracing mechanism would be extremely useful.
